"""End-to-end bounded rank-basis HyperSpline feasibility experiment.

Train on teacher-cache bags from explicitly named datasets and evaluate on
whole held-out datasets.  The fixed rank-R curve basis is fitted only from the
training datasets; query cross entropy through frozen TabICL is the only
learning signal.  Individual DirectSpline teachers are never imitation labels.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch import nn

from tabicl._hyperspline import HyperSplineTransform, summarize_context

try:
    from scripts.direct_spline_function_basis import TeacherBag, fit_pca
    from scripts.direct_spline_dataset_headroom import ensemble_metrics, release_cuda
    from scripts.direct_spline_multidataset_headroom import load_backbone
except ModuleNotFoundError:  # pragma: no cover
    from direct_spline_function_basis import TeacherBag, fit_pca
    from direct_spline_dataset_headroom import ensemble_metrics, release_cuda
    from direct_spline_multidataset_headroom import load_backbone


class RankBasisTransform(nn.Module):
    """Bounded, monotone piecewise-linear spline generated by HyperSpline's conditioner."""
    def __init__(self, mean: torch.Tensor, components: torch.Tensor, *, hidden_dim: int, target_aware: bool, raw_context: bool, coefficient_bound: float) -> None:
        super().__init__()
        self.rank, self.coefficient_bound = components.shape[0], coefficient_bound
        self.register_buffer("grid", torch.linspace(-4.0, 4.0, mean.numel()))
        self.register_buffer("mean_curve", mean)
        self.register_buffer("components", components)
        self.encoder = HyperSplineTransform(
            n_control_points=self.rank + 1, hidden_dim=hidden_dim, target_aware=target_aware,
            raw_context_residual=raw_context, generate_location=True, generate_scale=True,
            gate_initial_probability=0.01, raw_context_gate_initial_probability=0.01,
        )

    def values(self, x_context: torch.Tensor, y_context: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        stats = summarize_context(x_context, y_context=y_context.float().unsqueeze(0) if self.encoder.target_aware else None)
        raw, _ = self.encoder.generate_raw(stats, x_context=x_context, y_context=y_context.float().unsqueeze(0) if self.encoder.target_aware else None)
        coeff = self.coefficient_bound * torch.tanh(raw[..., :self.rank])
        candidate = self.grid.view(1, 1, -1) + self.mean_curve.view(1, 1, -1) + torch.matmul(coeff, self.components)
        # Differentiable monotone projection.  It is a linear spline, hence
        # still a spline transform, and cannot create arbitrary non-monotone
        # numerical preprocessing under dataset shift.
        increments = F.softplus(torch.diff(candidate, dim=-1) / 0.05) * 0.05
        values = torch.cat((candidate[..., :1], candidate[..., :1] + increments.cumsum(-1)), dim=-1)
        gate = torch.sigmoid(raw[..., self.rank]).unsqueeze(-1)
        values = self.grid.view(1, 1, -1) + gate * (values - self.grid.view(1, 1, -1))
        location = stats.location + stats.scale * torch.tanh(raw[..., self.rank + 1])
        scale = stats.scale * torch.exp(torch.tanh(raw[..., self.rank + 2]))
        return values, location, scale.clamp_min(1e-6)

    def transform(self, x: torch.Tensor, values: torch.Tensor, location: torch.Tensor, scale: torch.Tensor) -> torch.Tensor:
        z = (x.float() - location.unsqueeze(1)) / scale.unsqueeze(1)
        clamped = z.clamp(float(self.grid[0]), float(self.grid[-1]))
        position = (clamped - self.grid[0]) / (self.grid[-1] - self.grid[0]) * (self.grid.numel() - 1)
        left = position.floor().long().clamp(0, self.grid.numel() - 2)
        weight = (position - left).to(x.dtype)
        table = values.unsqueeze(1).expand(-1, x.shape[1], -1, -1)
        left_value = table.gather(3, left.unsqueeze(-1)).squeeze(-1)
        right_value = table.gather(3, (left + 1).unsqueeze(-1)).squeeze(-1)
        return left_value + weight * (right_value - left_value) + (z - clamped)

    def forward(self, x_context: torch.Tensor, y_context: torch.Tensor, x_query: torch.Tensor) -> torch.Tensor:
        values, location, scale = self.values(x_context, y_context)
        return torch.cat((self.transform(x_context, values, location, scale), self.transform(x_query, values, location, scale)), dim=1)


def args_parser() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--teacher-cache", type=Path, required=True)
    p.add_argument("--train-dataset", action="append", required=True)
    p.add_argument("--output-dir", type=Path, required=True)
    p.add_argument("--rank", type=int, default=8); p.add_argument("--steps", type=int, default=10000)
    p.add_argument("--lr", type=float, default=1e-3); p.add_argument("--hidden-dim", type=int, default=64)
    p.add_argument("--coefficient-bound", type=float, default=0.5); p.add_argument("--device", default="cuda")
    p.add_argument("--checkpoint", default=None); p.add_argument("--checkpoint-version", default="tabicl-classifier-v2-20260212.ckpt")
    p.add_argument("--target-aware", action="store_true"); p.add_argument("--raw-context", action="store_true")
    p.add_argument("--regularization", type=float, default=1e-4); p.add_argument("--seed", type=int, default=0)
    return p.parse_args()


def logits(backbone, model, context_x, context_y, query_x):
    backbone.clear_cache()
    return backbone(model(context_x, context_y, query_x), context_y.float().unsqueeze(0))


def main() -> None:
    args = args_parser(); torch.manual_seed(args.seed)
    payload = torch.load(args.teacher_cache.resolve(), map_location="cpu", weights_only=False)
    bags: list[TeacherBag] = payload["bags"]
    train_names = set(args.train_dataset); all_names = {bag.dataset for bag in bags}
    if not train_names < all_names: raise ValueError("train datasets must be a strict subset of cached datasets")
    train_bags = [bag for bag in bags if bag.dataset in train_names]
    curves = torch.cat([bag.curves for bag in train_bags]); mean, components, _ = fit_pca(curves)
    if args.rank > components.shape[0]: raise ValueError("rank unavailable")
    device = torch.device(args.device); backbone, _ = load_backbone(args, device)
    model = RankBasisTransform(mean.to(device), components[:args.rank].to(device), hidden_dim=args.hidden_dim, target_aware=args.target_aware, raw_context=args.raw_context, coefficient_bound=args.coefficient_bound).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    rng = np.random.default_rng(args.seed)
    for step in range(1, args.steps + 1):
        bag = train_bags[int(rng.integers(len(train_bags)))]
        context_x, context_y = bag.support_x.to(device), bag.support_y.to(device).long().squeeze(0)
        query_x = torch.as_tensor(bag.guard_x, dtype=torch.float32, device=device).unsqueeze(0)
        query_y = torch.as_tensor(bag.guard_y, dtype=torch.long, device=device).unsqueeze(0)
        objective = F.cross_entropy(logits(backbone, model, context_x, context_y, query_x).flatten(0, 1), query_y.flatten())
        values, _, _ = model.values(context_x, context_y)
        objective = objective + args.regularization * (values - model.grid.view(1, 1, -1)).square().mean()
        optimizer.zero_grad(set_to_none=True); objective.backward(); torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0); optimizer.step()
        if step == 1 or step % 500 == 0 or step == args.steps: print(f"step={step}/{args.steps} objective={float(objective):.6f}", flush=True)
    rows=[]; adapted=defaultdict(list); identity=defaultdict(list); labels={}
    for bag in [item for item in bags if item.dataset not in train_names]:
        context_x, context_y = bag.support_x.to(device), bag.support_y.to(device).long().squeeze(0)
        query_x = torch.as_tensor(bag.test_x, dtype=torch.float32, device=device).unsqueeze(0); target=torch.as_tensor(bag.test_y, dtype=torch.long)
        with torch.no_grad():
            adapted_prob=logits(backbone, model, context_x, context_y, query_x).softmax(-1).cpu()
            identity_x=(torch.cat((context_x,query_x),1)-context_x.mean(1,keepdim=True))/context_x.std(1,keepdim=True,unbiased=False).clamp_min(1e-6)
            backbone.clear_cache(); identity_prob=backbone(identity_x, context_y.float().unsqueeze(0)).softmax(-1).cpu()
        key=(bag.dataset,bag.seed); adapted[key].append(adapted_prob); identity[key].append(identity_prob); labels[key]=bag.test_y
        rows.append({"dataset":bag.dataset,"outer_seed":bag.seed,"bag":bag.bag,"adapted_loss":float(F.nll_loss(adapted_prob.log().flatten(0,1),target)),"identity_loss":float(F.nll_loss(identity_prob.log().flatten(0,1),target))})
        release_cuda(device)
    summary=[]
    for key in sorted(labels):
        al,aa=ensemble_metrics(adapted[key],labels[key]); il,ia=ensemble_metrics(identity[key],labels[key]); summary.append({"dataset":key[0],"outer_seed":key[1],"adapted_minus_identity_loss":al-il,"adapted_minus_identity_accuracy":aa-ia})
    out=args.output_dir.resolve(); out.mkdir(parents=True,exist_ok=True)
    with (out/"folds.csv").open("w",newline="",encoding="utf8") as f: w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
    (out/"summary.json").write_text(json.dumps({"train_datasets":sorted(train_names),"rank":args.rank,"target_aware":args.target_aware,"raw_context":args.raw_context,"runs":summary,"macro_loss_delta":float(np.mean([x["adapted_minus_identity_loss"] for x in summary])),"macro_accuracy_delta":float(np.mean([x["adapted_minus_identity_accuracy"] for x in summary]))},indent=2))

if __name__ == "__main__": main()
